[tools]
"github:FiloSottile/mkcert" = "latest"
"github:cloudflare/cloudflared" = "latest"
"github:coder/coder" = "latest"
"github:helix-editor/helix" = "latest"
"github:jesseduffield/lazydocker" = "latest"
"github:koekeishiya/yabai" = "latest"
"github:tuist/guck" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
